import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { join, relative, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { WebSocketServer, WebSocket } from 'ws';
import crypto from 'node:crypto';

const __dirname=fileURLToPath(new URL('.',import.meta.url));
const PORT=Number(process.env.PORT||10000),HOST=process.env.HOST||'0.0.0.0';
const WORLD_W=12000,WORLD_H=12000,MAX_PLAYERS=8,MAX_BYTES=64*1024;
const rooms=new Map(),clients=new Map();
const STATE_MS=50, SNAPSHOT_MS=100;
function safeRoom(v){const s=String(v??'').trim().toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,16);return s||'ABISMO01';}
function safeMode(v){const s=String(v??'teams').toLowerCase();return ['teams','ffa','coop'].includes(s)?s:'teams';}
function safeName(v){const s=String(v??'Nany').trim().slice(0,18);return s||'Nany';}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function randPos(seed){const x=(seed*1664525+1013904223)>>>0;const y=(x*1664525+1013904223)>>>0;return {x:400+(x/0xFFFFFFFF)*(WORLD_W-800),y:400+(y/0xFFFFFFFF)*(WORLD_H-800)};}
function roomFor(name){let r=rooms.get(name);if(!r){r=new Map();r.roomId=name;r.mode='teams';r.seed=crypto.randomBytes(4).readUInt32BE(0)||1;r.epochMs=Date.now();r.stage=0;r.removed=new Set();rooms.set(name,r);}return r;}
function publicPlayer(p){return {id:p.id,name:p.name,x:p.x,y:p.y,angle:p.angle,score:p.score,growthScore:p.growthScore,level:p.level,radius:p.radius,alive:p.alive,power:p.power,sprinting:p.sprinting,deaths:p.deaths,team:p.team||null,teamName:p.teamName||null};}
function send(ws,p){if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify(p));}
function broadcast(room,msg,except=null){for(const c of room.values())if(c.id!==except)send(c.ws,msg);}
function assignTeam(room,requested){if(room.mode!=='teams')return null;if(requested==='A'||requested==='B')return requested;const a=[...room.values()].filter(p=>p.team==='A').length,b=[...room.values()].filter(p=>p.team==='B').length;return a<=b?'A':'B';}
function teamName(t){return t==='A'?'Azul':t==='B'?'Rojo':null;}
function maxGrowth(room){return Math.max(0,...[...room.values()].map(p=>Number(p.score)||0));}
function evaluateStage(room){
  const max=maxGrowth(room);
  if(room.stage===0 && max>=1000){room.stage=1;broadcast(room,{type:'world_stage',stage:1,seed:room.seed,epochMs:room.epochMs});}
  else if(room.stage===2 && max>=3000){room.stage=3;broadcast(room,{type:'world_stage',stage:3,seed:room.seed,epochMs:room.epochMs});}
}
function removeClient(c){clients.delete(c.id);if(!c.joined||!c.room)return;const room=rooms.get(c.room);if(!room)return;room.delete(c.id);broadcast(room,{type:'player_left',id:c.id,room:c.room});if(room.size===0)rooms.delete(c.room);}
function acceptState(c,msg,now){if(now-c.lastStateAt<STATE_MS)return;c.lastStateAt=now;const nx=Number(msg.x),ny=Number(msg.y);if(Number.isFinite(nx)&&Number.isFinite(ny)){const d=Math.hypot(nx-c.x,ny-c.y);const dt=Math.max(.05,(now-c.lastAcceptedAt)/1000),maxStep=8.5*dt+24;if(d<=maxStep){c.x=clamp(nx,0,WORLD_W);c.y=clamp(ny,0,WORLD_H);}else{const t=Math.min(1,maxStep/Math.max(d,1));c.x+=(nx-c.x)*t;c.y+=(ny-c.y)*t;}}if(Number.isFinite(Number(msg.angle)))c.angle=Number(msg.angle);if(Number.isFinite(Number(msg.score)))c.score=Math.max(0,Math.min(1e6,Math.floor(Number(msg.score))));if(Number.isFinite(Number(msg.growthScore)))c.growthScore=Math.max(0,Math.min(1e6,Math.floor(Number(msg.growthScore))));if(Number.isFinite(Number(msg.radius)))c.radius=clamp(Number(msg.radius),4,320);c.level=Math.max(1,Number(msg.level)||1);c.power=Math.max(1,Math.min(10,Math.floor(1+Math.sqrt(Math.max(0,c.growthScore))/15)));c.alive=msg.alive!==false;c.sprinting=msg.sprinting===true;c.lastAcceptedAt=now;}
const http=createServer(async(req,res)=>{try{const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);const path=decodeURIComponent(url.pathname);if(path==='/health'){res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify({ok:true,rooms:rooms.size,players:clients.size}));return;}if(path==='/'||path==='/index.html'){const data=await readFile(join(__dirname,'index.html'));res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});res.end(data);return;}if(path==='/favicon.ico'){res.writeHead(204);res.end();return;}const fp=join(__dirname,path.replace(/^\/+/,''));const rel=relative(__dirname,fp);if(rel.startsWith('..')||rel.includes('\0')){res.writeHead(403);res.end('Forbidden');return;}const data=await readFile(fp);const ext=extname(fp);const type=ext==='.html'?'text/html; charset=utf-8':ext==='.js'||ext==='.mjs'?'text/javascript; charset=utf-8':ext==='.css'?'text/css; charset=utf-8':'application/octet-stream';res.writeHead(200,{'Content-Type':type,'Cache-Control':'no-store'});res.end(data);}catch(e){res.writeHead(e?.code==='ENOENT'?404:500);res.end(e?.code==='ENOENT'?'Not found':'Server error');}});
const wss=new WebSocketServer({noServer:true,maxPayload:MAX_BYTES});
http.on('upgrade',(req,sock,head)=>{const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(url.pathname!=='/ws'){sock.destroy();return;}wss.handleUpgrade(req,sock,head,ws=>wss.emit('connection',ws,req));});
wss.on('connection',ws=>{const id=crypto.randomUUID();const c={id,ws,room:null,joined:false,name:'Nany',x:WORLD_W/2,y:WORLD_H/2,angle:0,score:0,growthScore:0,level:1,power:1,radius:11,alive:true,sprinting:false,deaths:0,mode:'teams',team:null,teamName:null,lastStateAt:0,lastAcceptedAt:Date.now()};clients.set(id,c);ws.on('message',(data,binary)=>{if(binary||data.byteLength>MAX_BYTES)return;let msg;try{msg=JSON.parse(data.toString())}catch{return;}if(!msg||typeof msg.type!=='string')return;if(msg.type==='join'){if(c.joined)return;const roomName=safeRoom(msg.room),requested=safeMode(msg.mode),room=roomFor(roomName);if(room.size===0)room.mode=requested;if(room.mode!==requested){send(ws,{type:'error',message:`La sala ya es ${room.mode}.`});return;}if(room.size>=MAX_PLAYERS){send(ws,{type:'error',message:'Sala llena.'});return;}c.room=roomName;c.name=safeName(msg.name);c.mode=room.mode;c.team=assignTeam(room,msg.team);c.teamName=teamName(c.team);const pos=randPos(room.seed ^ id.length);c.x=pos.x;c.y=pos.y;c.joined=true;room.set(id,c);send(ws,{type:'welcome',id,room:roomName,mode:room.mode,team:c.team,teamName:c.teamName,worldSeed:room.seed,worldEpoch:room.epochMs,worldStage:room.stage,player:publicPlayer(c),players:[...room.values()].filter(p=>p.id!==id).map(publicPlayer),removed:[...room.removed]});broadcast(room,{type:'player_joined',player:publicPlayer(c),room:roomName},id);return;}if(!c.joined||!c.room)return;const room=rooms.get(c.room);if(!room)return;if(msg.type==='state'){acceptState(c,msg,Date.now());evaluateStage(room);return;}if(msg.type==='consume'){const entityId=String(msg.entityId||'');if(entityId&&entityId.startsWith('shared-')&&!room.removed.has(entityId)){room.removed.add(entityId);broadcast(room,{type:'entity_removed',entityId});}return;}if(msg.type==='boss_defeated'){if(room.stage===1){room.stage=2;room.removed.clear();broadcast(room,{type:'world_stage',stage:2,seed:room.seed,epochMs:room.epochMs});}else if(room.stage===3){room.stage=4;room.removed.clear();broadcast(room,{type:'world_stage',stage:4,seed:room.seed,epochMs:room.epochMs});}return;}if(msg.type==='leave'){try{ws.close()}catch{}}});ws.on('close',()=>removeClient(c));});
setInterval(()=>{const now=Date.now();for(const room of rooms.values()){evaluateStage(room);const players=[...room.values()].map(publicPlayer);for(const c of room.values())send(c.ws,{type:'snapshot',serverTime:now,room:room.roomId,mode:room.mode,population:room.size,worldStage:room.stage,players,removed:[...room.removed]});}},SNAPSHOT_MS);
http.listen(PORT,HOST,()=>console.log(`Nany deterministic multiplayer listening on http://${HOST}:${PORT}`));
