import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { WebSocketServer, WebSocket } from 'ws';
import crypto from 'node:crypto';

const ROOT=fileURLToPath(new URL('.',import.meta.url));
const PORT=Number(process.env.PORT||10000), HOST=process.env.HOST||'0.0.0.0';
const WW=12000, HH=12000, TICK=50, SNAP=100, MAX_PLAYERS=8, MAX_SPEED=3.2;
const rooms=new Map(), clients=new Map();
const TYPES=[
 {k:'plankton',v:'small',size:4,points:4,power:1,speed:.95},{k:'minnow',v:'small',size:8,points:8,power:2,speed:1.2},{k:'green',v:'small',size:11,points:13,power:3,speed:1.55},{k:'piranha',v:'small',size:14,points:21,power:4,speed:1.9},{k:'stick',v:'small',size:17,points:29,power:5,speed:1.45},{k:'rival',v:'small',size:21,points:40,power:6,speed:1.75},{k:'ray',v:'small',size:30,points:70,power:7,speed:2.05},{k:'monster',v:'small',size:43,points:115,power:9,speed:1.8},
 {k:'minnow_big',v:'big',size:8,points:12,power:3,speed:1.15},{k:'green_big',v:'big',size:11,points:19,power:4,speed:1.48},{k:'piranha_big',v:'big',size:14,points:30,power:5,speed:1.82},{k:'stick_big',v:'big',size:17,points:40,power:6,speed:1.4},{k:'rival_big',v:'big',size:21,points:55,power:7,speed:1.68},{k:'ray_big',v:'big',size:30,points:90,power:8,speed:1.98},{k:'monster_big',v:'big',size:43,points:145,power:10,speed:1.72}
];
const COLORS={plankton:'#8fffb0',minnow:'#bfe6ff',green:'#39ff6a',piranha:'#ff8a3d',stick:'#e0c66a',rival:'#a084ff',ray:'#6d8796',monster:'#8d2638',minnow_big:'#bfe6ff',green_big:'#39ff6a',piranha_big:'#ff8a3d',stick_big:'#e0c66a',rival_big:'#a084ff',ray_big:'#6d8796',monster_big:'#8d2638'};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const roomCode=v=>String(v||'ABISMO01').toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,16)||'ABISMO01';
const mode=v=>['teams','ffa','coop'].includes(v)?v:'teams';
const safeName=v=>String(v||'Nany').trim().slice(0,18)||'Nany';
const radius=s=>clamp(11+Math.sqrt(Math.max(0,s))*0.62,11,320);
const power=s=>s<100?1:s<250?2:s<500?3:s<900?4:s<1500?5:s<2500?6:s<4000?7:s<6000?8:s<9000?9:10;
const send=(ws,m)=>{if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify(m));};
const spawn=()=>({x:500+Math.random()*(WW-1000),y:500+Math.random()*(HH-1000)});
function teamFor(room,want){if(room.mode!=='teams')return null;const a=[...room.players.values()].filter(p=>p.team==='A').length,b=[...room.players.values()].filter(p=>p.team==='B').length;if((want==='A'||want==='B')&&Math.abs(a-b)<=1)return want;return a<=b?'A':'B';}
function publicPlayer(p){return{id:p.id,name:p.name,x:+p.x.toFixed(2),y:+p.y.toFixed(2),vx:+p.vx.toFixed(2),vy:+p.vy.toFixed(2),angle:+p.angle.toFixed(3),score:p.score,growthScore:p.growthScore,level:p.level,radius:+p.radius.toFixed(2),power:p.power,alive:p.alive,sprinting:p.sprinting,team:p.team||null,teamName:p.teamName||null};}
function fish(room){const tier=Math.random()<.28?'big':'small';const pool=TYPES.filter(t=>t.v===tier),t=pool[Math.floor(Math.random()*pool.length)],a=Math.random()*Math.PI*2,id='f'+room.next++;room.fish.set(id,{id,type:t.k,variant:t.v,size:t.size*(.95+Math.random()*.3),points:t.points,power:t.power,speed:t.speed,x:100+Math.random()*(WW-200),y:100+Math.random()*(HH-200),vx:Math.cos(a)*t.speed*.45,vy:Math.sin(a)*t.speed*.45,angle:a,phase:Math.random()*Math.PI*2});}
function ensureFish(room){while(room.fish.size<230)fish(room);}
function newRoom(code,mode){const r={code,mode,seed:crypto.randomBytes(4).readUInt32BE(0)||1,epoch:Date.now(),players:new Map(),spectators:new Set(),fish:new Map(),next:1,boss:null};ensureFish(r);return r;}
function nearest(room,e){let best=null,bd=Infinity;for(const p of room.players.values()){if(!p.alive)continue;const d=distance(e,p);if(d<bd){bd=d;best=p;}}return best;}
function updateFish(room,f,dt){const t=(Date.now()-room.epoch)/1000,p=nearest(room,f),pd=p?distance(f,p):Infinity,pr=p?radius(p.score):11,pp=p?power(p.score):0;let a=f.angle;if(p&&f.power>pp&&f.size>pr*.9&&pd<360)a=Math.atan2(p.y-f.y,p.x-f.x);else if(p&&f.power<pp&&pd<190)a=Math.atan2(f.y-p.y,f.x-p.x);else a=f.angle+Math.sin(t*.35+f.phase)*.22;f.angle+=(a-f.angle)*.08;f.vx+=(Math.cos(f.angle)*f.speed*.55-f.vx)*.1;f.vy+=(Math.sin(f.angle)*f.speed*.55-f.vy)*.1;f.x+=f.vx*dt*60;f.y+=f.vy*dt*60;if(f.x<70||f.x>WW-70){f.vx*=-1;f.x=clamp(f.x,70,WW-70);}if(f.y<70||f.y>HH-70){f.vy*=-1;f.y=clamp(f.y,70,HH-70);}}
function updateBoss(room,dt){const b=room.boss;if(!b)return;const p=nearest(room,b);if(p){const a=Math.atan2(p.y-b.y,p.x-b.x);b.angle+=(a-b.angle)*.06;b.vx+=(Math.cos(b.angle)*b.speed-b.vx)*.1;b.vy+=(Math.sin(b.angle)*b.speed-b.vy)*.1;}b.x+=b.vx*dt*60;b.y+=b.vy*dt*60;if(b.x<700||b.x>WW-700)b.vx*=-1;if(b.y<700||b.y>HH-700)b.vy*=-1;}
function snapshot(room,p){const entities=[...room.fish.values()].map(f=>({id:f.id,type:f.type,variant:f.variant,size:+f.size.toFixed(2),points:f.points,power:f.power,x:+f.x.toFixed(2),y:+f.y.toFixed(2),vx:+f.vx.toFixed(2),vy:+f.vy.toFixed(2),angle:+f.angle.toFixed(3),color:COLORS[f.type]||'#4fd1ff'}));if(room.boss)entities.push({...room.boss,boss:true,type:'boss',variant:'boss',color:'#ff6a3d'});return{type:'snapshot',serverTime:Date.now(),room:room.code,mode:room.mode,population:room.players.size,worldSeed:room.seed,worldEpoch:room.epoch,worldStage:room.boss?1:0,players:[...room.players.values()].map(publicPlayer),you:publicPlayer(p),player:publicPlayer(p),entities};}
function die(room,p,reason){if(!p.alive)return;p.alive=false;send(p.ws,{type:'player_dead',id:p.id,reason});setTimeout(()=>{if(!room.players.has(p.id))return;Object.assign(p,spawn(),{alive:true,vx:0,vy:0,inputX:0,inputY:0,targetSpeed:0,score:Math.floor(p.score*.5),growthScore:Math.floor(p.growthScore*.5)});p.radius=radius(p.score);p.power=power(p.score);p.invulnUntil=Date.now()+1200;send(p.ws,{type:'respawn',player:publicPlayer(p)});},1000);}
function applyInput(p,m){const x=Number(m.x),y=Number(m.y);if(!Number.isFinite(x)||!Number.isFinite(y))return;const dx=x-p.reportX,dy=y-p.reportY,d=Math.hypot(dx,dy);p.reportX=x;p.reportY=y;if(d>.15&&d<120){p.inputX=dx/d;p.inputY=dy/d;p.targetSpeed=Math.min(MAX_SPEED,d*20);}else p.targetSpeed=0;p.lastInput=Date.now();p.sprinting=!!m.sprinting;}
function movePlayer(p,dt){if(!p.alive)return;const tx=p.inputX*p.targetSpeed,ty=p.inputY*p.targetSpeed;p.vx+=(tx-p.vx)*.30;p.vy+=(ty-p.vy)*.30;if(Date.now()-p.lastInput>250){p.vx*=.72;p.vy*=.72;p.targetSpeed=0;}p.x=clamp(p.x+p.vx*dt*60,p.radius,WW-p.radius);p.y=clamp(p.y+p.vy*dt*60,p.radius,HH-p.radius);if(Math.abs(p.vx)+Math.abs(p.vy)>.05)p.angle=Math.atan2(p.vy,p.vx);}
function collisions(room){for(const p of room.players.values()){if(!p.alive)continue;for(const f of room.fish.values()){const d=distance(p,f);if(d>p.radius+f.size*.65)continue;if(f.variant==='small'&&f.power<p.power&&f.size<p.radius){room.fish.delete(f.id);p.score+=f.points;p.growthScore=p.score;p.radius=radius(p.score);p.power=power(p.score);break;}if(f.variant==='big'&&f.power>p.power&&f.size>p.radius&&Date.now()>p.invulnUntil){die(room,p,'fish');break;}}}const ps=[...room.players.values()].filter(p=>p.alive);for(let i=0;i<ps.length;i++)for(let j=i+1;j<ps.length;j++){const a=ps[i],b=ps[j];if(room.mode==='coop'||(room.mode==='teams'&&a.team===b.team))continue;if(distance(a,b)>a.radius*.8+b.radius*.8)continue;if(a.score>=b.score+1&&a.radius>b.radius){a.score+=Math.max(10,Math.floor(b.score*.25));a.growthScore=a.score;a.radius=radius(a.score);a.power=power(a.score);die(room,b,'player');}else if(b.score>=a.score+1&&b.radius>a.radius){b.score+=Math.max(10,Math.floor(a.score*.25));b.growthScore=b.score;b.radius=radius(b.score);b.power=power(b.score);die(room,a,'player');}}}
function spectatorBridge(){return `<script>(function(){'use strict';const WW=12000,HH=12000;let ws=null,room=null,world=null,mini=null;const get=n=>{try{return window.eval('typeof '+n+'!=="undefined"?'+n+':undefined')}catch(_){return undefined}};const online=()=>{const M=get('Multiplayer');return !!(M&&M.isConnected&&M.isConnected())};function hook(){for(const n of ['updateSpawns','updateEntity','handleCollisions']){const old=window[n];if(typeof old==='function'&&!old.__nany){const f=function(...a){if(online())return;return old.apply(this,a)};f.__nany=true;window[n]=f;}}const oldDraw=window.drawEntities;if(typeof oldDraw==='function'&&!oldDraw.__nany){const f=function(...a){if(online())return;return oldDraw.apply(this,a)};f.__nany=true;window.drawEntities=f;}const oldMove=window.updatePlayer;if(typeof oldMove==='function'&&!oldMove.__nany){const f=function(dt){if(!online())return oldMove(dt);const g=get('game'),K=get('Keys');if(!g||!g.player)return oldMove(dt);let ax=0,ay=0;if(K?.arrowup||K?.w)ay--;if(K?.arrowdown||K?.s)ay++;if(K?.arrowleft||K?.a)ax--;if(K?.arrowright||K?.d)ax++;const len=Math.hypot(ax,ay)||1;const sp=2.5;g.player.vx+=(ax/len*sp-g.player.vx)*.18;g.player.vy+=(ay/len*sp-g.player.vy)*.18;g.player.x=clamp(g.player.x+g.player.vx,0,WW);g.player.y=clamp(g.player.y+g.player.vy,0,HH);if(ax||ay)g.player.angle=Math.atan2(g.player.vy,g.player.vx)};f.__nany=true;window.updatePlayer=f;}}
function drawWorld(){if(!world||!online())return;const c=get('canvas'),ctx=get('ctx'),fish=get('drawFish');const cam=get('camera'),zf=get('getViewZoom');if(!c||!ctx||!fish||!world.you)return;const z=typeof zf==='function'?zf():1;const cx=cam?.x??(world.you.x-c.width/(2*z)),cy=cam?.y??(world.you.y-c.height/(2*z));for(const e of world.entities||[]){const sx=(e.x-cx)*z,sy=(e.y-cy)*z;if(sx<-150||sy<-150||sx>c.width+150||sy>c.height+150)continue;fish(sx,sy,Math.max(3,(e.size||8)*z),e.color||'#4fd1ff',e.angle||0,false);}for(const p of world.players||[]){if(!p.alive||p.id===world.you.id)continue;const sx=(p.x-cx)*z,sy=(p.y-cy)*z;if(sx<-150||sy<-150||sx>c.width+150||sy>c.height+150)continue;fish(sx,sy,Math.max(10,(p.radius||18)*z),p.team===world.you.team?'#5ea7ff':'#ff5a5a',p.angle||0,false);ctx.save();ctx.fillStyle='#fff';ctx.font='700 10px monospace';ctx.textAlign='center';ctx.fillText(p.name||'Jugador',sx,sy-(p.radius||18)*z-7);ctx.restore();}}
function drawMini(){if(!mini||!world?.you)return;const c=mini.getContext('2d');c.clearRect(0,0,180,180);c.fillStyle='rgba(2,11,20,.82)';c.fillRect(0,0,180,180);c.strokeStyle='rgba(77,255,240,.32)';c.strokeRect(1,1,178,178);for(const p of world.players||[]){c.fillStyle=p.id===world.you.id?'#4dfff0':(p.team===world.you.team?'#5ea7ff':'#ff5a5a');c.beginPath();c.arc(p.x/WW*180,p.y/HH*180,p.id===world.you.id?5:4,0,Math.PI*2);c.fill();}}
function tick(){hook();const M=get('Multiplayer'),r=M&&M.room?M.room():null;if(online()&&r&&r!==room){room=r;try{ws?.close()}catch(_){}ws=new WebSocket((location.protocol==='https:'?'wss':'ws')+'://'+location.host+'/ws');ws.onopen=()=>ws.send(JSON.stringify({type:'spectator',room:r}));ws.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.type!=='snapshot')return;world=m;const g=get('game');if(g&&m.you){g.player.x=m.you.x;g.player.y=m.you.y;g.player.vx=m.you.vx;g.player.vy=m.you.vy;g.score=m.you.score;g.growthScore=m.you.growthScore;}}catch(_){}};}else if(!online()){room=null;world=null;try{ws?.close()}catch(_){}ws=null;if(mini)mini.style.display='none';}if(online()){const g=get('game');if(g)g.entities=[];drawWorld();if(mini){mini.style.display='block';drawMini();}}requestAnimationFrame(tick)}function init(){mini=document.createElement('canvas');mini.width=180;mini.height=180;mini.id='authoritativeMiniMap';Object.assign(mini.style,{position:'fixed',right:'18px',bottom:'18px',width:'180px',height:'180px',zIndex:'9999',pointerEvents:'none',borderRadius:'12px',display:'none'});document.body.appendChild(mini);requestAnimationFrame(tick)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();})();</script>`;}
const http=createServer(async(req,res)=>{try{const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(u.pathname==='/health'){res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});return res.end(JSON.stringify({ok:true,rooms:rooms.size,players:clients.size}));}if(u.pathname==='/'||u.pathname==='/index.html'){let html=await readFile(join(ROOT,'index.html'),'utf8');html=html.replace('</body>',spectatorBridge()+'</body>');res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return res.end(html);}res.writeHead(404);res.end('Not found')}catch(e){res.writeHead(500);res.end('Server error')}});
const wss=new WebSocketServer({server:http});
wss.on('connection',ws=>{const id=crypto.randomUUID();const c={id,ws,joined:false,spectator:false,room:null,name:'Nany',x:WW/2,y:HH/2,vx:0,vy:0,inputX:0,inputY:0,targetSpeed:0,reportX:WW/2,reportY:HH/2,angle:0,score:0,growthScore:0,level:1,power:1,radius:11,alive:true,sprinting:false,team:null,lastInput:Date.now(),invulnUntil:0};clients.set(id,c);ws.on('message',raw=>{let m;try{m=JSON.parse(raw.toString())}catch{return;}if(m.type==='spectator'){const r=rooms.get(roomCode(m.room));if(!r)return;c.spectator=true;c.room=r.code;return send(ws,snapshot(r,c));}if(m.type==='join'){if(c.joined)return;const rm=rooms.get(roomCode(m.room))||(()=>{const r=newRoom(roomCode(m.room),mode(m.mode));rooms.set(r.code,r);return r})();if(rm.players.size>=MAX_PLAYERS)return send(ws,{type:'error',message:'Sala llena'});c.room=rm.code;c.name=safeName(m.name);c.team=teamFor(rm,m.team);c.joined=true;Object.assign(c,spawn());c.reportX=c.x;c.reportY=c.y;rm.players.set(c.id,c);return send(ws,snapshot(rm,c));}if(!c.joined)return;const rm=rooms.get(c.room);if(!rm)return;if(m.type==='state')applyInput(c,m);else if(m.type==='leave')ws.close();});ws.on('close',()=>{clients.delete(id);if(c.joined&&c.room){const r=rooms.get(c.room);if(r){r.players.delete(id);if(!r.players.size)rooms.delete(r.code);}}});});
let last=Date.now(),lastSnap=0;setInterval(()=>{const now=Date.now(),dt=Math.min(.05,(now-last)/1000);last=now;for(const r of rooms.values()){for(const p of r.players.values())movePlayer(p,dt);for(const f of r.fish.values())updateFish(r,f,dt);if(r.boss)updateBoss(r,dt);const top=Math.max(0,...[...r.players.values()].map(p=>p.score));if(!r.boss&&top>=2000)r.boss={id:'boss-'+Math.random().toString(36).slice(2),type:'boss',size:180,speed:1.7,x:WW/2,y:HH/2,vx:1,vy:.4,angle:.4,power:99};if(r.fish.size<230)for(let i=r.fish.size;i<230;i++)fish(r);collisions(r);if(now-lastSnap>=SNAP){lastSnap=now;for(const r2 of rooms.values()){for(const p of r2.players.values())send(p.ws,snapshot(r2,p));for(const c2 of clients.values())if(c2.spectator&&c2.room===r2.code)send(c2.ws,snapshot(r2,c2));}}}},TICK);
http.listen(PORT,HOST,()=>console.log(`NANY AUTHORITATIVE V3 ${HOST}:${PORT}`));
