const WORLD_W=12000, WORLD_H=12000;
const TICK_HZ=30, SNAP_HZ=20;
const MAX_PLAYERS=8, FISH_N=260;
const GEM_FISH_CAP=Math.max(1,Math.round(FISH_N*0.01));
const GEM_SPAWN_INTERVAL_MS=45000;
const HEARTBEAT_MS=15000, RESUME_MS=10*60*1000;
const FISH_RESPAWN_MS=1600, CHASE_MS=1000, PREDATOR_BITE_ARM_MS=900, BOSS_HITS=5;
const PET_KEYS=new Set(['none','turtle','crab','puffer','dolphin','ray']);

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const send=(ws,msg)=>{if(ws?.readyState===1)ws.send(JSON.stringify(msg));};
const sendAll=(w,msg)=>{for(const p of w.players.values())if(p.connected)send(p.ws,msg);};
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const safeName=v=>String(v||'Nany').trim().slice(0,18)||'Nany';
const makeId=prefix=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
const makeDeviceId=()=>`nany-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`;
const worldForMode=v=>v==='ffa'||v==='pvp'?['PVP','ffa']:v==='coop'||v==='pve'?['PVE','coop']:['EQUIPO','teams'];
const radius=growth=>clamp(11+Math.sqrt(Math.max(0,growth))*0.62,11,320);
const playerHB=growth=>radius(growth)*0.78;
const fishHB=f=>Math.max(2.5,f.size*0.88);
const stageLevel=stage=>stage<=1?1:stage<=3?2:stage<=5?3:4;
const isBossStage=stage=>stage===1||stage===3||stage===5;
const isPredator=f=>f?.role==='predator'||f?.role==='hunter';
const normalizeTeam=v=>{const s=String(v||'').trim().toLowerCase();if(s==='a'||s==='azul'||s==='blue'||s==='team a'||s==='equipo a'||s==='equipo azul')return'A';if(s==='b'||s==='rojo'||s==='red'||s==='team b'||s==='equipo b'||s==='equipo rojo')return'B';return null;};

const FISH={
  gem:{key:'gemFish',role:'prey',points:4,color:'#57ff63',size:9,speed:0.85,gemFish:true,renderKey:'gemFish'},
  plankton:{key:'plankton',role:'prey',points:4,color:'#8fffb0',size:4,speed:2.10},
  minnow:{key:'minnow',role:'prey',points:8,color:'#bfe6ff',size:8,speed:2.55},
  green:{key:'green',role:'prey',points:16,color:'#39ff6a',size:10,speed:2.95},
  silver:{key:'silver',role:'prey',points:24,color:'#d9f2ff',size:13,speed:3.20},
  piranha:{key:'piranha',role:'predator',points:35,color:'#ff8a3d',size:14,speed:4.25},
  stick:{key:'stick',role:'predator',points:50,color:'#e0c66a',size:17,speed:3.85},
  rival:{key:'rival',role:'predator',points:75,color:'#a084ff',size:21,speed:4.40},
  lantern:{key:'lantern',role:'predator',points:105,color:'#d92828',size:24,speed:4.35,light:true,minLevel:2,renderKey:'lava'},
  shark:{key:'shark',role:'predator',points:150,color:'#6d8796',size:31,speed:4.95},
  monster:{key:'monster',role:'predator',points:300,color:'#8d2638',size:44,speed:4.55}
};

const LEVEL_POOLS={
  1:[['plankton',88],['minnow',54],['green',30],['piranha',32],['stick',24],['rival',18],['shark',10],['monster',4]],
  2:[['plankton',68],['minnow',50],['green',28],['silver',12],['piranha',28],['stick',20],['rival',18],['lantern',18],['shark',10],['monster',8]],
  3:[['plankton',58],['minnow',44],['green',30],['silver',14],['piranha',28],['stick',20],['rival',20],['lantern',24],['shark',12],['monster',10]],
  4:[['plankton',50],['minnow',40],['green',30],['silver',16],['piranha',28],['stick',20],['rival',20],['lantern',28],['shark',16],['monster',12]]
};
function weightedType(level,index){const pool=LEVEL_POOLS[level]||LEVEL_POOLS[4];let n=((index%FISH_N)+FISH_N)%FISH_N;for(const [key,count] of pool){if(n<count)return FISH[key];n-=count;}return FISH.monster;}
function rng(seed){let s=(seed>>>0)||1;return()=>{s^=s<<13;s>>>=0;s^=s>>>17;s>>>=0;return((s^=s<<5)>>>0)/4294967296;};}
function randomSpawn(margin=500){return{x:margin+Math.random()*(WORLD_W-margin*2),y:margin+Math.random()*(WORLD_H-margin*2)};}
function safeFishPos(w,r=Math.random){for(let tries=0;tries<12;tries++){const pos={x:220+r()*(WORLD_W-440),y:220+r()*(WORLD_H-440)};let okay=true;for(const p of w.players.values())if(p.connected&&p.alive&&Math.hypot(pos.x-p.x,pos.y-p.y)<340){okay=false;break;}if(okay)return pos;}return{x:220+r()*(WORLD_W-440),y:220+r()*(WORLD_H-440)};}
function normalFish(w,index,r=Math.random){const level=stageLevel(w.stage),t=weightedType(level,index),a=r()*Math.PI*2;const predScale=t.role==='predator'?(1.05+r()*0.72)*(1+(level-1)*0.27):(0.88+r()*0.24)*(1+(level-1)*0.04);const size=t.size*predScale,speed=t.speed*(0.93+r()*0.16)*(1+(level-1)*0.045),pos=safeFishPos(w,r);return{id:`${w.code}-fish-${index}-${w.nextFish++}`,index,type:t.key,role:t.role,points:t.points,color:t.color,size,speed,baseSpeed:speed,x:pos.x,y:pos.y,vx:Math.cos(a)*speed*.90,vy:Math.sin(a)*speed*.90,angle:a,heading:a,turn:.30+r()*.75,chaseId:null,chaseUntil:0,chaseStartedAt:0,cooldownUntil:0,light:!!t.light,hazard:null,immortal:false,gemFish:false,renderKey:t.renderKey||t.key};}
function gemFish(w,index,x,y){const t=FISH.gem,a=Math.random()*Math.PI*2;return{id:`${w.code}-gem-${w.nextGem++}`,index,type:t.key,role:t.role,points:t.points,color:t.color,size:t.size,speed:t.speed,baseSpeed:t.speed,x,y,vx:Math.cos(a)*t.speed*.65,vy:Math.sin(a)*t.speed*.65,angle:a,heading:a,turn:.75+Math.random()*1.4,chaseId:null,chaseUntil:0,chaseStartedAt:0,cooldownUntil:0,light:false,hazard:null,immortal:false,gemFish:true,renderKey:t.renderKey};}
function makeLavaHazard(w){const pos=safeFishPos(w),a=Math.random()*Math.PI*2,speed=4.70;return{id:`${w.code}-lava-hazard`,index:-1,type:'lava',role:'predator',points:0,color:'#7a0f16',size:48,speed,baseSpeed:speed,x:pos.x,y:pos.y,vx:Math.cos(a)*speed*.82,vy:Math.sin(a)*speed*.82,angle:a,heading:a,turn:.55,chaseId:null,chaseUntil:0,chaseStartedAt:0,cooldownUntil:0,hazard:'lava',immortal:true,light:false,gemFish:false,renderKey:'lava'};}
function makeBoss(w,type){const r=rng((w.seed^((w.stage+1)*0x9E3779B1))>>>0),a=r()*Math.PI*2;const sizes={shrimp:105,lava:118,jelly:128},speeds={shrimp:3.80,lava:4.45,jelly:3.90};return{id:`${w.code}-boss-${w.stage}`,type:'boss',boss:true,bossType:type,x:1000+r()*(WORLD_W-2000),y:1000+r()*(WORLD_H-2000),vx:Math.cos(a)*speeds[type]*.76,vy:Math.sin(a)*speeds[type]*.76,angle:a,heading:a,size:sizes[type],speed:speeds[type],hits:0,chasing:false,chaseId:null,chaseUntil:0,cooldownUntil:0,vulnerableUntil:type==='shrimp'?Infinity:0,turn:.55+r()*.8};}
function scheduleNextGem(w,now=Date.now(),first=false){w.nextGemAt=now+(first?20000+Math.random()*20000:GEM_SPAWN_INTERVAL_MS);}
function makeWorld(code,mode){const w={code,mode,seed:(Math.random()*0xffffffff)>>>0,epoch:Date.now(),stage:0,bossCleared:false,tick:0,nextFish:1,nextGem:1,nextGemAt:0,players:new Map(),fish:new Map(),respawns:[],boss:null,lavaHazard:null};populateWorld(w);return w;}
const worlds=new Map([['PVP',makeWorld('PVP','ffa')],['PVE',makeWorld('PVE','coop')],['EQUIPO',makeWorld('EQUIPO','teams')]]);
function populateWorld(w){w.fish.clear();w.respawns=[];w.nextFish=1;w.nextGem=1;if(isBossStage(w.stage)){scheduleNextGem(w,Date.now(),true);return;}const r=rng((w.seed^((w.stage+1)*0x85EBCA6B))>>>0);for(let i=0;i<FISH_N;i++){const f=normalFish(w,i,r);w.fish.set(f.id,f);}scheduleNextGem(w,Date.now(),true);}
function activeGemCount(w){let n=0;for(const f of w.fish.values())if(f.gemFish)n++;return n;}
function maybeSpawnGem(w,now){if(isBossStage(w.stage)||now<w.nextGemAt||activeGemCount(w)>=GEM_FISH_CAP)return;const candidates=[...w.fish.values()].filter(f=>!f.gemFish&&!f.immortal&&!f.hazard&&f.role==='prey');if(!candidates.length){scheduleNextGem(w,now);return;}const old=candidates[Math.floor(Math.random()*candidates.length)];w.fish.delete(old.id);const g=gemFish(w,old.index,old.x,old.y);w.fish.set(g.id,g);scheduleNextGem(w,now);sendAll(w,{type:'gem_spawned',entity:pubFish(g),serverTime:now});}
function startBoss(w,type){w.bossCleared=false;w.fish.clear();w.respawns=[];w.boss=makeBoss(w,type);scheduleNextGem(w,Date.now(),true);if(w.stage===1&&!w.lavaHazard)w.lavaHazard=makeLavaHazard(w);}
function teamFor(w,want){if(w.mode!=='teams')return null;want=normalizeTeam(want);const a=[...w.players.values()].filter(p=>p.connected&&normalizeTeam(p.team)==='A').length,b=[...w.players.values()].filter(p=>p.connected&&normalizeTeam(p.team)==='B').length;if(want&&Math.abs(a-b)<=1)return want;return a<=b?'A':'B';}
function pubPlayer(p){const team=normalizeTeam(p.team);return{id:p.id,name:p.name,deviceId:p.deviceId,x:+p.x.toFixed(2),y:+p.y.toFixed(2),vx:+p.vx.toFixed(2),vy:+p.vy.toFixed(2),angle:+p.angle.toFixed(3),score:Math.floor(p.score),growthScore:Math.floor(p.growthScore),radius:+radius(p.growthScore).toFixed(2),level:p.level,lives:p.lives,maxLives:p.maxLives||1,alive:p.alive,sprinting:p.sprinting,pet:p.pet||'none',team,teamName:team==='A'?'Azul':team==='B'?'Rojo':null};}
function pubFish(f){const now=Date.now();return{id:f.id,sharedId:f.id,type:f.type,role:isPredator(f)?'predator':f.role,points:f.points,size:+f.size.toFixed(2),color:f.color,x:+f.x.toFixed(2),y:+f.y.toFixed(2),vx:+f.vx.toFixed(3),vy:+f.vy.toFixed(3),angle:+f.angle.toFixed(3),hazard:f.hazard||null,immortal:!!f.immortal,light:!!f.light,gemFish:!!f.gemFish,renderKey:f.renderKey||f.type,chasing:!!f.chaseId&&f.chaseUntil>now,chaseRemainingMs:Math.max(0,f.chaseUntil-now)};}
function pubBoss(b){if(!b)return null;const now=Date.now(),active=!!b.chaseId&&b.chasing&&b.chaseUntil>now;return{id:b.id,type:'boss',boss:true,bossType:b.bossType,x:+b.x.toFixed(2),y:+b.y.toFixed(2),vx:+b.vx.toFixed(3),vy:+b.vy.toFixed(3),angle:+b.angle.toFixed(3),size:b.size,hits:b.hits,chasing:active,chaseRemainingMs:Math.max(0,b.chaseUntil-now),cooldownRemainingMs:Math.max(0,b.cooldownUntil-now),vulnerableTail:b.bossType==='shrimp'||now<b.vulnerableUntil};}
function snapshot(w){const entities=[...w.fish.values()].map(pubFish);if(w.lavaHazard)entities.push(pubFish(w.lavaHazard));return{type:'snapshot',room:w.code,mode:w.mode,population:[...w.players.values()].filter(p=>p.connected).length,serverTick:w.tick,serverTime:Date.now(),worldSeed:w.seed,worldEpoch:w.epoch,worldStage:w.stage,bossCleared:w.bossCleared,boss:pubBoss(w.boss),gemFishActive:activeGemCount(w),gemFishCap:GEM_FISH_CAP,nextGemAt:w.nextGemAt,players:[...w.players.values()].filter(p=>p.connected).map(pubPlayer),entities};}
function broadcast(w){const base=snapshot(w);for(const p of w.players.values())if(p.connected)send(p.ws,{...base,you:pubPlayer(p),player:pubPlayer(p)});}
function broadcastStage(w){sendAll(w,{type:'world_stage',stage:w.stage,bossCleared:w.bossCleared,serverTime:Date.now(),worldSeed:w.seed,worldEpoch:w.epoch,boss:pubBoss(w.boss)});broadcast(w);}
function maybeStartBoss(w){if(w.boss||w.bossCleared)return;const maxScore=Math.max(0,...[...w.players.values()].map(p=>p.score||0));if(w.stage===0&&maxScore>=1000){w.stage=1;startBoss(w,'shrimp');broadcastStage(w);}else if(w.stage===2&&maxScore>=3000){w.stage=3;startBoss(w,'lava');broadcastStage(w);}else if(w.stage===4&&maxScore>=6000){w.stage=5;startBoss(w,'jelly');broadcastStage(w);}}
function canPlayerEat(p,f){return !!f.gemFish||(!f.immortal&&f.role==='prey'&&fishHB(f)<playerHB(p.growthScore)*0.96);}
function canFishEatPlayer(p,f){return isPredator(f)&&fishHB(f)>=playerHB(p.growthScore)*1.04;}
function disengageFish(w,f,now){const old=f.chaseId?w.players.get(f.chaseId):null;f.chaseId=null;f.chaseUntil=0;f.chaseStartedAt=0;f.role='predator';f.speed=f.baseSpeed||f.speed;f.cooldownUntil=now+(f.hazard==='lava'?4200:2800);if(old){const away=Math.atan2(f.y-old.y,f.x-old.x)+(Math.random()-.5)*.35;f.heading=away;const s=f.speed*.82;f.vx=Math.cos(away)*s;f.vy=Math.sin(away)*s;}f.turn=.35+Math.random()*.55;}
function updateOneFish(w,f,dt,players){const now=Date.now();if(!f.baseSpeed)f.baseSpeed=f.speed;const predator=isPredator(f);if(predator)f.speed=f.baseSpeed;let target=f.chaseId&&f.chaseUntil>now?w.players.get(f.chaseId):null;if(target&&(!target.connected||!target.alive||!predator))target=null;if(f.chaseId&&(!target||f.chaseUntil<=now)){disengageFish(w,f,now);target=null;}const detect=f.hazard==='lava'?400:clamp(260+f.size*1.30,280,390);if(predator&&!target&&!f.chaseId&&f.cooldownUntil<=now){let best=null,bd=Infinity;for(const p of players){const dd=dist(f,p);if(canFishEatPlayer(p,f)&&dd<detect&&dd<bd){best=p;bd=dd;}}if(best){target=best;f.role='hunter';f.chaseId=best.id;f.chaseStartedAt=now;f.chaseUntil=now+CHASE_MS;}}
if(target){const age=now-(f.chaseStartedAt||now),dd=dist(f,target);if(dd>detect+145){disengageFish(w,f,now);target=null;}else{f.role='hunter';const a=Math.atan2(target.y-f.y,target.x-f.x),chaseSpeed=f.speed*(age<180 ? .94 : 1.08);f.heading=a;f.vx+=(Math.cos(a)*chaseSpeed-f.vx)*.58;f.vy+=(Math.sin(a)*chaseSpeed-f.vy)*.58;}}
if(!target){if(isPredator(f))f.role='predator';if(f.turn<=0){f.turn=.30+Math.random()*.80;f.heading+=(Math.random()-.5)*1.20;}else f.turn-=dt;f.vx+=(Math.cos(f.heading)*f.speed*.94-f.vx)*.12;f.vy+=(Math.sin(f.heading)*f.speed*.94-f.vy)*.12;}const maxSpeed=target?f.speed*1.08:f.speed,sp=Math.hypot(f.vx,f.vy)||.001;if(sp>maxSpeed){f.vx=f.vx/sp*maxSpeed;f.vy=f.vy/sp*maxSpeed;}f.x+=f.vx*dt*60;f.y+=f.vy*dt*60;const m=f.hazard==='lava'?120:80;if(f.x<m){f.x=m;f.vx=Math.abs(f.vx);f.heading=Math.atan2(f.vy,f.vx);}if(f.x>WORLD_W-m){f.x=WORLD_W-m;f.vx=-Math.abs(f.vx);f.heading=Math.atan2(f.vy,f.vx);}if(f.y<m){f.y=m;f.vy=Math.abs(f.vy);f.heading=Math.atan2(f.vy,f.vx);}if(f.y>WORLD_H-m){f.y=WORLD_H-m;f.vy=-Math.abs(f.vy);f.heading=Math.atan2(f.vy,f.vx);}f.angle=Math.atan2(f.vy,f.vx);}
function updateFish(w,dt){const players=[...w.players.values()].filter(p=>p.connected&&p.alive),now=Date.now();for(let i=w.respawns.length-1;i>=0;i--){const rr=w.respawns[i];if(now<rr.at)continue;const f=normalFish(w,rr.index);w.fish.set(f.id,f);w.respawns.splice(i,1);}maybeSpawnGem(w,now);for(const f of w.fish.values())updateOneFish(w,f,dt,players);if(w.lavaHazard)updateOneFish(w,w.lavaHazard,dt,players);}
function disengageBoss(w,b,now){const old=b.chaseId?w.players.get(b.chaseId):null;b.chaseId=null;b.chaseUntil=0;b.chasing=false;b.cooldownUntil=now+(b.bossType==='shrimp'?3800:b.bossType==='lava'?3400:3600);if(b.bossType!=='shrimp')b.vulnerableUntil=now+1100;if(old){const away=Math.atan2(b.y-old.y,b.x-old.x)+(Math.random()-.5)*.28;b.heading=away;const s=b.speed*(b.bossType==='shrimp'?.42:.60);b.vx=Math.cos(away)*s;b.vy=Math.sin(away)*s;}b.turn=.45+Math.random()*.55;}
function updateBoss(w,dt){const b=w.boss;if(!b)return;const now=Date.now(),players=[...w.players.values()].filter(p=>p.connected&&p.alive);let target=b.chaseId&&b.chaseUntil>now?w.players.get(b.chaseId):null;if(target&&(!target.connected||!target.alive))target=null;if(b.chaseId&&(!target||b.chaseUntil<=now)){disengageBoss(w,b,now);target=null;}const detect=b.bossType==='shrimp'?170:b.bossType==='lava'?190:205;if(!target&&!b.chaseId&&b.cooldownUntil<=now){let best=null,bd=Infinity;for(const p of players){const dd=dist(b,p);if(dd<detect&&dd<bd){best=p;bd=dd;}}if(best){target=best;b.chaseId=best.id;b.chaseUntil=now+CHASE_MS;b.chasing=true;if(b.bossType==='lava')b.vulnerableUntil=0;}}if(target){const a=Math.atan2(target.y-b.y,target.x-b.x),mul=b.bossType==='lava'?1.18:b.bossType==='jelly'?1.10:1.08;b.heading=a;b.vx+=(Math.cos(a)*b.speed*mul-b.vx)*.30;b.vy+=(Math.sin(a)*b.speed*mul-b.vy)*.30;}else if(b.turn<=0){b.turn=.55+Math.random()*1.0;b.heading+=(Math.random()-.5)*(b.bossType==='jelly'?.65:1.0);}else b.turn-=dt;if(!target){const resting=now<b.cooldownUntil;const drift=resting?(b.bossType==='shrimp'?.26:b.bossType==='lava'?.42:.38):(b.bossType==='jelly'?.74:.84);b.vx+=(Math.cos(b.heading)*b.speed*drift-b.vx)*(resting?.13:.09);b.vy+=(Math.sin(b.heading)*b.speed*drift-b.vy)*(resting?.13:.09);}b.x+=b.vx*dt*60;b.y+=b.vy*dt*60;const m=260;if(b.x<m){b.x=m;b.vx=Math.abs(b.vx);}if(b.x>WORLD_W-m){b.x=WORLD_W-m;b.vx=-Math.abs(b.vx);}if(b.y<m){b.y=m;b.vy=Math.abs(b.vy);}if(b.y>WORLD_H-m){b.y=WORLD_H-m;b.vy=-Math.abs(b.vy);}b.angle=Math.atan2(b.vy,b.vx);}
function killPlayer(w,p,reason,eater=null,killerFish=null){if(!p.alive)return false;const now=Date.now(),remaining=Math.max(0,(Number(p.lives)||1)-1),finalDeath=remaining<=0;p.alive=false;p.lives=remaining;p.vx=0;p.vy=0;p.lastDeathReason=reason;p.lastDeathBossType=killerFish?.boss?killerFish.bossType:null;p.lastDeathAt=now;const victim=pubPlayer(p),eaterPub=eater?pubPlayer(eater):null,killerFishPub=killerFish?(killerFish.boss?pubBoss(killerFish):pubFish(killerFish)):null;sendAll(w,{type:'player_death',victimId:p.id,victim,reason,eaterId:eater?.id||null,eater:eaterPub,killerFish:killerFishPub,finalDeath,lives:remaining,maxLives:p.maxLives||1,worldStage:w.stage,bossCleared:w.bossCleared,boss:pubBoss(w.boss),serverTime:now});if(eater)sendAll(w,{type:'player_eaten',victimId:p.id,victim,eaterId:eater.id,eater:eaterPub,reason,finalDeath,serverTime:now});send(p.ws,{type:'player_dead',id:p.id,reason,finalDeath,lives:remaining,maxLives:p.maxLives||1,worldStage:w.stage,bossCleared:w.bossCleared,boss:pubBoss(w.boss)});broadcast(w);if(finalDeath)return true;setTimeout(()=>{const q=w.players.get(p.id);if(!q||q.alive)return;const pos=randomSpawn();q.x=pos.x;q.y=pos.y;q.lastX=pos.x;q.lastY=pos.y;q.vx=0;q.vy=0;if(reason!=='boss'){q.score=Math.max(0,Math.floor(q.score*.5));q.growthScore=Math.max(0,Math.floor(q.growthScore*.5));}q.alive=true;q.level=stageLevel(w.stage);q.invulnerableUntil=Date.now()+1800;q.lastInputAt=Date.now();send(q.ws,{type:'respawn',player:pubPlayer(q),worldStage:w.stage,bossCleared:w.bossCleared,boss:pubBoss(w.boss)});broadcast(w);},1200);return true;}
function removeFish(w,p,f){if(!w.fish.has(f.id)||f.immortal)return false;const eaten=pubFish(f);w.fish.delete(f.id);p.score+=f.points;p.growthScore+=f.points;w.respawns.push({index:f.index,at:Date.now()+FISH_RESPAWN_MS});if(f.gemFish)w.nextGemAt=Math.max(w.nextGemAt,Date.now()+GEM_SPAWN_INTERVAL_MS);sendAll(w,{type:'entity_removed',entityId:f.id,entity:eaten,by:p.id,eater:pubPlayer(p),serverTick:w.tick,serverTime:Date.now()});if(f.gemFish)send(p.ws,{type:'gem_reward',amount:1,entityId:f.id,serverTime:Date.now()});return true;}
function tryConsume(w,p,id){const f=w.fish.get(String(id||''));if(!f||!p.connected||!p.alive)return false;const reach=playerHB(p.growthScore)+fishHB(f)+70;if(dist(p,f)>reach||!canPlayerEat(p,f))return false;const ok=removeFish(w,p,f);if(ok){maybeStartBoss(w);broadcast(w);}return ok;}
function bossTarget(b){const a=b.angle||0;if(b.bossType==='shrimp')return{x:b.x-Math.cos(a)*b.size*1.12,y:b.y-Math.sin(a)*b.size*1.12,r:b.size*.36};if(b.bossType==='lava')return{x:b.x-Math.cos(a)*b.size*.92,y:b.y-Math.sin(a)*b.size*.92,r:b.size*.32};return{x:b.x,y:b.y-b.size*.18,r:b.size*.40};}
function tryBossHit(w,p,bossId){const b=w.boss;if(!b||b.id!==String(bossId||'')||!p.alive||w.bossCleared)return false;const target=bossTarget(b),dd=Math.hypot(p.x-target.x,p.y-target.y),vulnerable=b.bossType==='shrimp'||Date.now()<b.vulnerableUntil||!b.chasing;if(!vulnerable||dd>playerHB(p.growthScore)+target.r+42)return false;const now=Date.now();if(p.lastBossHitAt&&now-p.lastBossHitAt<650)return false;p.lastBossHitAt=now;b.hits=Math.min(BOSS_HITS,b.hits+1);sendAll(w,{type:'boss_state',boss:pubBoss(b),by:p.id,serverTime:now});if(b.hits>=BOSS_HITS){w.bossCleared=true;const type=b.bossType;w.boss=null;sendAll(w,{type:'boss_cleared',stage:w.stage,bossType:type,serverTime:now});broadcast(w);}return true;}
function combat(w){const now=Date.now();for(const p of w.players.values()){if(!p.connected||!p.alive||p.invulnerableUntil>now||now-(p.lastInputAt||0)>450)continue;const ph=playerHB(p.growthScore);for(const f of w.fish.values()){const fh=fishHB(f),dd=dist(p,f);if(dd>ph+fh)continue;if(canPlayerEat(p,f)){removeFish(w,p,f);continue;}const armed=(f.chaseStartedAt||0)>0&&now-f.chaseStartedAt>=PREDATOR_BITE_ARM_MS;if(canFishEatPlayer(p,f)&&f.chaseId===p.id&&f.chaseUntil>now&&armed){killPlayer(w,p,'fish',null,f);break;}}if(!p.alive)continue;const h=w.lavaHazard;const hazardArmed=h&&(h.chaseStartedAt||0)>0&&now-h.chaseStartedAt>=PREDATOR_BITE_ARM_MS;if(h&&dist(p,h)<=ph+fishHB(h)&&h.chaseId===p.id&&h.chaseUntil>now&&hazardArmed){killPlayer(w,p,'fish',null,h);continue;}const b=w.boss;if(b&&b.chasing&&b.chaseId===p.id&&b.chaseUntil>now&&dist(p,b)<=ph+b.size*.65){killPlayer(w,p,'boss',null,b);continue;}}const ps=[...w.players.values()].filter(p=>p.connected&&p.alive&&now-(p.lastInputAt||0)<=450);for(let i=0;i<ps.length;i++)for(let j=i+1;j<ps.length;j++){const a=ps[i],b=ps[j],at=normalizeTeam(a.team),bt=normalizeTeam(b.team);if(w.mode==='coop'||(w.mode==='teams'&&at&&bt&&at===bt))continue;const ar=radius(a.growthScore),br=radius(b.growthScore),dd=dist(a,b);if(dd>ar*.82+br*.82)continue;if(a.growthScore>b.growthScore*1.04&&ar>br*1.02){a.score+=Math.max(10,Math.floor(b.score*.25));a.growthScore+=Math.max(10,Math.floor(b.growthScore*.25));killPlayer(w,b,'player',a);}else if(b.growthScore>a.growthScore*1.04&&br>ar*1.02){b.score+=Math.max(10,Math.floor(a.score*.25));b.growthScore+=Math.max(10,Math.floor(a.growthScore*.25));killPlayer(w,a,'player',b);}}maybeStartBoss(w);}
function applyInput(w,p,m){const x=Number(m.x),y=Number(m.y),now=Date.now();if(!Number.isFinite(x)||!Number.isFinite(y)||!p.alive)return;if(PET_KEYS.has(String(m.pet||'')))p.pet=String(m.pet);const dt=Math.max(.016,Math.min(.35,(now-p.lastInputAt)/1000)),dx=x-p.x,dy=y-p.y,dd=Math.hypot(dx,dy),maxPerSecond=p.sprinting?3400:2100,allowed=Math.max(140,maxPerSecond*dt),ratio=dd>allowed&&dd>0?allowed/dd:1,nx=clamp(p.x+dx*ratio,0,WORLD_W),ny=clamp(p.y+dy*ratio,-100,WORLD_H+120);p.vx=(nx-p.x)/Math.max(dt,.001)/60;p.vy=(ny-p.y)/Math.max(dt,.001)/60;p.x=nx;p.y=ny;p.lastX=x;p.lastY=y;p.angle=Number.isFinite(Number(m.angle))?Number(m.angle):Math.atan2(p.vy,p.vx);p.sprinting=!!m.sprinting;p.lastInputAt=now;const reportedLevel=clamp(Math.floor(Number(m.level)||p.level),1,4);if(w.stage===1&&w.bossCleared&&reportedLevel>=2){w.stage=2;w.bossCleared=false;w.boss=null;w.lavaHazard=null;for(const q of w.players.values()){q.level=2;q.growthScore=0;}populateWorld(w);broadcastStage(w);}else if(w.stage===3&&w.bossCleared&&reportedLevel>=3){w.stage=4;w.bossCleared=false;w.boss=null;for(const q of w.players.values())q.level=3;populateWorld(w);broadcastStage(w);}else if(w.stage===5&&w.bossCleared&&reportedLevel>=4){w.stage=6;w.bossCleared=false;w.boss=null;for(const q of w.players.values())q.level=4;populateWorld(w);broadcastStage(w);}}
function devSetMass(w,p,value){const v=clamp(Math.floor(Number(value)||0),0,100000);p.score=v;p.growthScore=v;p.lives=p.maxLives||1;p.alive=true;p.invulnerableUntil=Date.now()+1500;maybeStartBoss(w);broadcast(w);return v;}
function devSetStage(w,stage){const s=clamp(Math.floor(Number(stage)||0),0,6);w.stage=s;w.bossCleared=false;w.boss=null;w.lavaHazard=null;for(const p of w.players.values()){p.level=stageLevel(s);p.alive=true;p.lives=p.maxLives||1;p.lastDeathReason=null;p.lastDeathBossType=null;p.lastDeathAt=0;p.invulnerableUntil=Date.now()+1500;}if(s===1)startBoss(w,'shrimp');else if(s===3)startBoss(w,'lava');else if(s===5)startBoss(w,'jelly');else populateWorld(w);broadcastStage(w);return s;}

export {WORLD_W,WORLD_H,TICK_HZ,SNAP_HZ,MAX_PLAYERS,FISH_N,GEM_FISH_CAP,GEM_SPAWN_INTERVAL_MS,HEARTBEAT_MS,RESUME_MS,worlds,worldForMode,randomSpawn,stageLevel,teamFor,pubPlayer,snapshot,broadcast,sendAll,send,updateFish,updateBoss,combat,applyInput,tryConsume,tryBossHit,devSetMass,devSetStage,safeName,makeId,makeDeviceId};